name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
    
    - name: Install mise
      run: |
        curl -fsSL https://mise.run | sh
        echo "$HOME/.local/bin" >> $GITHUB_PATH
        
    - name: Install Tuist
      run: |
        ~/.local/bin/mise install tuist@latest
        ~/.local/bin/mise use tuist@latest
        ~/.local/bin/mise use -g tuist@latest  

    - name: Install Tuist via Mise Action
      uses: jdx/mise-action@v2
      with:
        tools: tuist@latest 
    
    - name: Check Tuist path
      run: |
        export PATH="$HOME/.local/bin:$PATH"
        which tuist
        tuist version
    
    - name: Cache Tuist
      uses: actions/cache@v3
      with:
        path: |
          ~/.tuist
          .tuist
        key: ${{ runner.os }}-tuist-${{ hashFiles('**/Package.resolved') }}
        restore-keys: |
          ${{ runner.os }}-tuist-

    - name: Generate PrivateKey.swift from Secret
      run: |
        mkdir -p Tuist/ProjectDescriptionHelpers
        cat <<EOF > Tuist/ProjectDescriptionHelpers/PrivateKey.swift
        import Foundation

        public enum PrivateKey {
            public static let teamID: String = "${{ secrets.APPLE_TEAM_ID }}"
        }
        EOF

    - name: Check PrivateKey file
      run: |
        sed -n '1,5p' Tuist/ProjectDescriptionHelpers/PrivateKey.swift
    
    - name: Install dependencies
      run: |
        export PATH="$HOME/.local/bin:$PATH"
        tuist install
      
    - name: Generate project
      run: |
        export PATH="$HOME/.local/bin:$PATH"
        tuist generate
      
    - name: Build project
      run: |
        xcodebuild -workspace BuyingMyHome.xcworkspace \
                   -scheme BuyingMyHome \
                   -destination 'platform=iOS Simulator,name=iPhone 15 Pro,OS=17.5' \
            CODE_SIGNING_ALLOWED=NO \
                   build
                   
    - name: Run tests
      run: |
        xcodebuild -workspace BuyingMyHome.xcworkspace \
                   -scheme BuyingMyHome \
                   -destination 'platform=iOS Simulator,name=iPhone 15 Pro,OS=17.5' \
                   test
                   
  lint:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install SwiftLint
      run: brew install swiftlint
      
    - name: Run SwiftLint
      run: swiftlint --strict 