name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
    
    - name: Install Tuist
      run: |
        curl -Ls https://install.tuist.io | bash
        
    - name: Cache Tuist
      uses: actions/cache@v3
      with:
        path: |
          ~/.tuist
          .tuist
        key: ${{ runner.os }}-tuist-${{ hashFiles('**/Package.resolved') }}
        restore-keys: |
          ${{ runner.os }}-tuist-
    
    - name: Install dependencies
      run: tuist install
      
    - name: Generate project
      run: tuist generate
      
    - name: Build for release
      run: |
        xcodebuild -workspace BuyingMyHome.xcworkspace \
                   -scheme BuyingMyHome-PROD \
                   -configuration Release \
                   -destination generic/platform=iOS \
                   archive -archivePath BuyingMyHome.xcarchive
                   
    - name: Export IPA
      run: |
        xcodebuild -exportArchive \
                   -archivePath BuyingMyHome.xcarchive \
                   -exportPath ./export \
                   -exportOptionsPlist ExportOptions.plist
                   
    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false 